[cf2x_L250]
acc_coef = 0.0
cmd_f_coef = 0.97732585
thrust_time_coef = 0.0858607
rpy_coef = [-245.67, -245.67, -227.78]
rpy_rates_coef = [-17.32, -17.32, -25.63]
cmd_rpy_coef = [196.18, 196.18, 390.27]


[cf2x_P250]
acc_coef = 0.0
cmd_f_coef = 0.98323006
thrust_time_coef = 0.0578952
rpy_coef = [-319.14, -319.14, -284.28]
rpy_rates_coef = [-20.85, -20.85, -38.43]
cmd_rpy_coef = [263.30, 263.30, 502.58]


[cf2x_T350]
acc_coef = 0.0
cmd_f_coef = 0.86259295 
thrust_time_coef = 0.05062676
rpy_coef = [-267.14, -267.14, -126.49]
rpy_rates_coef = [-19.48, -19.48, -14.41]
cmd_rpy_coef = [200.90, 200.90, 193.11]


[cf21B_500]
acc_coef = 0.0
cmd_f_coef = 0.96841816
thrust_time_coef = 0.02055366
rpy_coef = [-188.9910, -188.9910, -138.3109]
rpy_rates_coef = [-12.7803, -12.7803, -16.8485]
cmd_rpy_coef = [138.0834, 138.0834, 198.5161]