# Since the first principles models only rely on physical parameters, 
# which are already defined in data/params.toml, this file is intentionally left empty.

[cf2x_L250]


[cf2x_P250]


[cf2x_T350]


[cf21B_500]