[cf2x_L250]
acc_coef = 0.0
cmd_f_coef = 0.98325003    
thrust_time_coef = 0.12116392
drag_matrix = [
    [-0.01471782, 0.0,         0.0         ],
    [0.0,         -0.01471782, 0.0         ],
    [0.0,         0.0,         -0.01277641 ]
]
rpy_coef = [-245.67, -245.67, -227.78]
rpy_rates_coef = [-17.32, -17.32, -25.63]
cmd_rpy_coef = [196.18, 196.18, 390.27]


[cf2x_P250]
acc_coef = 0.0
cmd_f_coef = 0.99085062
thrust_time_coef = 0.11554009
drag_matrix = [
    [-0.01351483, 0.0,         0.0         ],
    [0.0,         -0.01351483, 0.0         ],
    [0.0,         0.0,         -0.01677452 ]
]
rpy_coef = [-319.14, -319.14, -284.28]
rpy_rates_coef = [-20.85, -20.85, -38.43]
cmd_rpy_coef = [263.30, 263.30, 502.58]


[cf2x_T350]
acc_coef = 0.0
cmd_f_coef = 0.87242516    
thrust_time_coef = 0.13701907
drag_matrix = [
    [-0.01556697, 0.0,         0.0         ],
    [0.0,         -0.01556697, 0.0         ],
    [0.0,         0.0,         -0.02191672 ]
]
rpy_coef = [-267.14, -267.14, -126.49]
rpy_rates_coef = [-19.48, -19.48, -14.41]
cmd_rpy_coef = [200.90, 200.90, 193.11]


[cf21B_500]
acc_coef = 0.0
cmd_f_coef = 0.98023254
thrust_time_coef = 0.07993871
drag_matrix = [
    [-0.02149163, 0.0,          0.0         ],
    [0.0,         -0.02149163,  0.0         ],
    [0.0,         0.0,          -0.02359736 ]
]
rpy_coef = [-188.9910, -188.9910, -138.3109]
rpy_rates_coef = [-12.7803, -12.7803, -16.8485]
cmd_rpy_coef = [138.0834, 138.0834, 198.5161]
