[cf2x_L250]
acc_coef = 0.0
cmd_f_coef = 1.0627
thrust_time_coef = 0.1891
drag_matrix = [
    [-0.0177, 0.0,     0.0     ],
    [0.0,     -0.0177, 0.0     ],
    [0.0,     0.0,     -0.0177 ]
]
rpy_coef = [-257.2, -257.2, 225.3]
rpy_rates_coef = [-20.2, -20.2, -28.61]
cmd_rpy_coef = [207.1, 207.1, 392.7]

# TODO: Check if parameters are correct
[cf2x_P250]
acc_coef = 0.0
cmd_f_coef = 1.0627
thrust_time_coef = 0.1891
drag_matrix = [
    [-0.0177, 0.0,     0.0     ],
    [0.0,     -0.0177, 0.0     ],
    [0.0,     0.0,     -0.0177 ]
]
rpy_coef = [-257.2, -257.2, -225.3]
rpy_rates_coef = [-20.2, -20.2, -28.61]
cmd_rpy_coef = [207.1, 207.1, 392.7]

# TODO: Check if parameters are correct
[cf2x_T350]
acc_coef = 0.0
cmd_f_coef = 1.0627
thrust_time_coef = 0.1891
drag_matrix = [
    [-0.0177, 0.0,     0.0     ],
    [0.0,     -0.0177, 0.0     ],
    [0.0,     0.0,     -0.0177 ]
]
rpy_coef = [-257.2, -257.2, -225.3]
rpy_rates_coef = [-20.2, -20.2, -28.61]
cmd_rpy_coef = [207.1, 207.1, 392.7]


[cf21B_500]
acc_coef = 0.0
cmd_f_coef = 0.98023254
thrust_time_coef = 0.07993871
drag_matrix = [
    [-0.02149163, 0.0,          0.0         ],
    [0.0,         -0.02149163,  0.0         ],
    [0.0,         0.0,          -0.02359736 ]
]
rpy_coef = [-188.9910, -188.9910, -138.3109]
rpy_rates_coef = [-12.7803, -12.7803, -16.8485]
cmd_rpy_coef = [138.0834, 138.0834, 198.5161]
